-- 1 Сессия
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT SUM(rating) FROM pizzeria;
SELECT SUM(rating) FROM pizzeria;
COMMIT;
SELECT SUM(rating) FROM pizzeria;

-- 2 Сессия
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
INSERT INTO pizzeria VALUES(11,'Kazan Pizza 2',4);
COMMIT;
SELECT SUM(rating) FROM pizzeria;