stages:
  - build
Build:
  stage: build
  script:
    - cd src/cat
    - make s21_cat
    - cd ../
    - cd src/grep
    - make s21_grep
  artifacts:
    paths:
      - src/grep/s21_grep
      - src/cat/s21_cat
    expire_in: 30 days
